# Generated by Django 2.0.2 on 2018-02-13 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
            ],
        ),
    ]
