# Generated by Django 2.0.2 on 2018-02-14 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=5)),
                ('test_date', models.DateTimeField()),
                ('test_details', models.TextField()),
                ('result_status', models.CharField(max_length=10)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
            ],
        ),
    ]
