# Generated by Django 2.0.2 on 2018-02-15 23:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=5)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('test_details', models.TextField(null=True)),
                ('result_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('C', 'Completed')], max_length=10, null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
            ],
        ),
    ]
