# Generated by Django 2.0.2 on 2018-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='result_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('C', 'Completed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='test_details',
            field=models.TextField(null=True),
        ),
    ]
