# Generated by Django 2.0.2 on 2018-02-14 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_auto_20180214_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
