# Generated by Django 2.0.2 on 2018-02-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('records', '0002_auto_20180214_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('visit_reason', models.CharField(max_length=150)),
                ('doctor', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='employees.Employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Patient')),
            ],
            options={
                'ordering': ('appointment_date', 'appointment_time'),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=1)),
                ('prescribed', models.CharField(max_length=150)),
                ('record_date', models.DateTimeField(auto_now=True)),
                ('visit_record', models.TextField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.CompleteAppointment')),
            ],
        ),
    ]
